server:
  port: 8888

spring:
  application:
    name: sbms-config-server
  
  cloud:
    config:
      server:
        git:
          # Using the main branch for stability
          uri: https://github.com/Thareesha98/config-repo.git
          default-label: test
          
          # Forces the server to download the latest config on startup
          clone-on-start: false
          
          # Allows you to put config files in subfolders like 'config/' or 'sbms/'
          search-paths: '{application}' 
          
          # Recommended: Skip SSL validation if using internal git, 
          # but for GitHub public repos, this isn't strictly needed.
          strict-host-key-checking: false

management:
  endpoints:
    web:
      exposure:

        # Fixed: "actuator" is the path, "*" or specific names are the inclusions
        include: "health,info,bus-refresh,refresh"
  endpoint:
    health:
      show-details: true

